### PR TITLE
Update to Swift 3 / Xcode 8.1

### PR DESCRIPTION
**Pull request by jmnavarro**
Update to Swift 3 / Xcode 8.1. Many of your dispatch_* functions are deprecated / obsolete now.

### CODE REVIEW

**Comment by utdrmac** [comment]
Apologies for piggybacking on this PR, but I have a question and I think you are a more advanced Swift developer than I. I am trying to query an HTTP REST/API every X seconds. The thought was to use DispatchQueues somehow. The best option so far that seems to work is:

```
func getEvents() {
  URLSession(configuration:).dataTask(with:) {
   ... after processing the returned data, the completion block simply does a myqueue.asyncAfter(5 seconds) { getEvents() }
  }
}
```

This seems very javascript-ish to me a la `setTimeout(callYourself,5000)`. I was using Timer() but that doesn't prevent simultaneous execution.

Do you know of a better way to continuously call a function in Swift? This is my producer. My consumer is a func that uses an infinite while to pop off elements of an array and process them. If the array becomes empty, it too does an asyncAfter() to call itself. Thanks!

**Comment by jmnavarro** [comment]
I don't see anything wrong in your solution.
As an alternative, you can create a single-fire timer, but it does basically the same as `queue.asyncAfter(x)`

**Comment by utdrmac** [comment]
*phew* I feel better now. Thanks!

**Comment by jmnavarro** [comment]
hahaha, don't trust me so blindly! 😂

**Pull request merged**
